### PR TITLE
Add content on SSH Agent

### PR DESCRIPTION
**Pull request by MattSurabian**
dat agent. :eyeglasses:

### CODE REVIEW

**Comment by tkellen** [comment]
We should also mention that this makes ssh agent forwarding possible (and perhaps include that as an exercise, having people run `ssh -T git@github.com` with and without agent on their remote server).

**Comment by tkellen** [comment]
I'm not actually clear on how this happens, but it seems we should also mention that ssh-agent will try every loaded private key during a connection attempt, vs the usage of `-i` which only tries the private key you provide.

**Comment by tkellen** [comment]
PS: this is a great start! <3

**Comment by MattSurabian** [comment]
Regarding the looping behavior that's specific to SSH itself and not directly SSH agent isn't it? While `-i` loads a specific key it was always my thought that the looping was part of SSH itself, maybe that's my misunderstanding?

I'm down to explore forwarding though it's not something I use often and don't think we're going to cover it more in the class. Maybe a short blurb near the end would suffice? I think doing the `-T` exercise might be a waste of cycles but I could be totally off base here and am curious to hear yall's thoughts.

**Comment by tkellen** [comment]
We use forwarding on basically every app deployment @ Bocoup (checking out repos on behalf of the deploying user). I think the `ssh -T` exercise is important because it gives people a vector to see that ssh-agent is forwarding properly in a specific context they will likely care about (when forwarding is working, github will say hello (your github username here), and when it isn't, you'll get access denied).

When running through this workshop one-on-one I've often told people that any time there is a problem with ansible you can drop down to ssh to confirm your assumptions about things working. For example, `ssh -i keyfile user@server` maps to `ansible-playbook --private-key keyfile -u user`.

**Comment by MattSurabian** [comment]
Updated with content about looping and forwarding

**Comment by tkellen** [comment]
:+1:

**Comment by tkellen** [comment]
I'll make a few updates and do a PR as per usual. Thank @MattSurabian !!

**Pull request merged**
