### PR TITLE
edits for known-hosts

### PR DESCRIPTION
**Pull request by tkellen**
cc @MattSurabian

### CODE REVIEW

**Comment by MattSurabian** [comment]
Might want to keep in the bit about `vagrant

**Comment by MattSurabian** [comment]
:+1:

**Comment by tkellen** [comment]
Roger that, I'll put it back and merge.

**Comment by tkellen** [comment]
I added it to the checklist:
https://github.com/tkellen/learn-deployment/commit/bda895da10bb86aa08dc20acdfb809e6c5ffbe88

**Comment by MattSurabian** [comment]
Yep, nice

**Pull request merged**
